// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Tool: project_hydrate_config
 *
 * Writes the current provisioning state (tenant, client, container type,
 * container, subscription/RG) into a project so a reference app can consume it
 * directly. Emits `.env`, `appsettings.Development.json`, and `azure.yaml`
 * fragments. Ports EVAL.md `hydrate-config`.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { buildAzureYaml, findArchitecture } from "../reference-architectures.js";
import { readState } from "../state.js";
import { LOCAL_SPA_REDIRECT_URI } from "../constants.js";
import type { McpTool } from "../types.js";

interface HydrateArgs {
  targetDir?: string;
  formats?: string[];
}

/** Config outputs this tool can emit — must mirror the inputSchema enum. */
const VALID_FORMATS = ["env", "appsettings", "azureyaml"] as const;

function envFile(s: ReturnType<typeof readState>): string {
  const lines = [
    "# SharePoint Embedded configuration (generated by project_hydrate_config)",
    `TENANT_ID=${s.tenantId ?? ""}`,
    `CLIENT_ID=${s.appId ?? ""}`,
    `CONTAINER_TYPE_ID=${s.containerTypeId ?? ""}`,
    `CONTAINER_ID=${s.containerId ?? ""}`,
    "",
    "# Vite-exposed copies — a frontend SPA only sees import.meta.env.VITE_* vars.",
    `VITE_TENANT_ID=${s.tenantId ?? ""}`,
    `VITE_CLIENT_ID=${s.appId ?? ""}`,
    `VITE_CONTAINER_TYPE_ID=${s.containerTypeId ?? ""}`,
    `VITE_CONTAINER_ID=${s.containerId ?? ""}`,
  ];
  if (s.azureSubscriptionId) lines.push(`AZURE_SUBSCRIPTION_ID=${s.azureSubscriptionId}`);
  if (s.resourceGroup) lines.push(`AZURE_RESOURCE_GROUP=${s.resourceGroup}`);
  return lines.join("\n") + "\n";
}

function appSettings(s: ReturnType<typeof readState>): string {
  return JSON.stringify(
    {
      SharePointEmbedded: {
        TenantId: s.tenantId ?? "",
        ClientId: s.appId ?? "",
        ContainerTypeId: s.containerTypeId ?? "",
        ContainerId: s.containerId ?? "",
      },
    },
    null,
    2,
  ) + "\n";
}

/**
 * Offline, NON-BLOCKING sign-in warnings for the hydrated config.
 *
 * This tool is deterministic/offline (and its unit tests do not mock Graph), so
 * it cannot read the live app registration back. It only flags what is checkable
 * from state: a blank tenant id makes the SPA's MSAL authority
 * (`https://login.microsoftonline.com/<tenant>`) invalid, so sign-in fails
 * before any redirect-URI check. Returns human-readable lines; never throws.
 */
function signInConfigWarnings(s: ReturnType<typeof readState>): string[] {
  const warnings: string[] = [];
  if (!s.tenantId || s.tenantId.trim() === "") {
    warnings.push(
      "`TENANT_ID` / `VITE_TENANT_ID` is empty — MSAL builds its sign-in authority from the " +
        "tenant id, so the SPA cannot sign in until a tenant is provisioned (`project_provision`).",
    );
  }
  return warnings;
}

/**
 * Persistent, copy-pasteable advisory appended to hydrate OUTPUT (never to
 * `.env`) telling the user to confirm the emitted `VITE_CLIENT_ID` /
 * `VITE_TENANT_ID` actually match the app registration they are looking at, and
 * to verify that exact app lists the local SPA redirect URI.
 *
 * A stale/mismatched `.env` is the most common cause of `AADSTS9002326`
 * ("I added the redirect URI and sign-in still fails" — it was added to a
 * DIFFERENT app than the one baked into `.env`). Purely informational: it does
 * not block, open a browser, or throw.
 */
function signInVerificationAdvisory(s: ReturnType<typeof readState>): string {
  const clientId = s.appId ?? "";
  const lookup = s.appObjectId
    ? "applications/" + s.appObjectId + "?$select=appId,spa"
    : "applications?$filter=appId eq '" + clientId + "'&$select=appId,spa";
  return (
    "\n\n> **Before you sign in — verify this `.env` targets the right app.** A stale or " +
    "mismatched `VITE_CLIENT_ID` / `VITE_TENANT_ID` is the most common cause of the " +
    "`AADSTS9002326` sign-in error: the SPA authenticates as the app baked into `.env`, which " +
    "may be a *different* registration than the one you added the redirect URI to.\n>\n" +
    "> 1. Confirm these match the app in the portal (Entra ID > App registrations > Overview): " +
    "Application (client) ID `" +
    clientId +
    "`" +
    (s.tenantId ? " and Directory (tenant) ID `" + s.tenantId + "`" : "") +
    ".\n>\n" +
    "> 2. Confirm that exact app lists `" +
    LOCAL_SPA_REDIRECT_URI +
    "` as a Single-page application (SPA) redirect URI:\n>\n" +
    ">    ```bash\n" +
    '>    az rest --method GET --uri "https://graph.microsoft.com/v1.0/' +
    lookup +
    '"\n' +
    ">    ```\n>\n" +
    "> If it is missing, re-run `project_app_create` / `project_provision` (which self-repairs " +
    "it) or add it in the portal. Vite bakes `.env` in at build time, so rebuild after any change."
  );
}

/**
 * Build the `azure.yaml` (azd) descriptor that matches the architecture the user
 * actually scaffolded. The previous implementation emitted a constant
 * (name `spe-app`, language `ts`, host `staticwebapp`) which clobbered a C#
 * App Service scaffold — flipping it to a Static Web App and renaming the
 * service. We derive name/language/host from the recorded scaffold instead.
 */
function azureYaml(s: ReturnType<typeof readState>): string {
  const name = s.projectName ?? "spe-app";
  const arch = s.scaffoldArchitecture ? findArchitecture(s.scaffoldArchitecture) : undefined;
  if (arch) {
    return buildAzureYaml(name, arch.language, arch.host);
  }
  // No architecture recorded — fall back to the React/Static Web Apps default
  // (the recommended architecture), but still honor the project name.
  return buildAzureYaml(name, "ts", "staticwebapp");
}

interface YamlBlock {
  key: string;
  lines: string[];
}

/**
 * Parse a YAML document into its top-level key blocks. A block is a top-level
 * `key:` line plus all subsequent indented / blank / comment continuation lines
 * until the next top-level key. Leading comments before the first key stay out
 * of the block model — the existing file is preserved verbatim, so they are
 * never lost.
 */
function parseTopLevelBlocks(yaml: string): YamlBlock[] {
  const blocks: YamlBlock[] = [];
  let current: YamlBlock | null = null;
  for (const line of yaml.split(/\r?\n/)) {
    const m = /^([A-Za-z_][\w-]*):/.exec(line);
    if (m) {
      current = { key: m[1], lines: [line] };
      blocks.push(current);
    } else if (current && (/^\s+/.test(line) || line.trim() === "" || line.startsWith("#"))) {
      current.lines.push(line);
    }
  }
  return blocks;
}

/**
 * Merge a generated `azure.yaml` into an existing (scaffolded / user-edited) one
 * WITHOUT overwriting anything already present. The scaffold is authoritative
 * for architecture-specific values (service name, language, host) and the user
 * may have added custom content; we therefore only APPEND the top-level blocks
 * the existing file is missing and preserve everything else verbatim
 * ("truly merge, don't clobber").
 *
 * Returns the merged content and the list of top-level keys that were filled in
 * (empty when the existing file already covered everything → preserve verbatim).
 */
export function mergeAzureYaml(
  existing: string,
  generated: string,
): { content: string; filled: string[] } {
  const haveKeys = new Set(parseTopLevelBlocks(existing).map((b) => b.key));
  const additions: string[] = [];
  const filled: string[] = [];
  for (const block of parseTopLevelBlocks(generated)) {
    if (!haveKeys.has(block.key)) {
      additions.push(block.lines.join("\n").replace(/\n+$/, ""));
      filled.push(block.key);
    }
  }
  if (additions.length === 0) {
    return { content: existing, filled: [] };
  }
  const base = existing.endsWith("\n") ? existing : existing + "\n";
  return { content: base + additions.join("\n") + "\n", filled };
}

export const hydrateConfigTool: McpTool = {
  name: "project_hydrate_config",
  annotations: { plane: "control" },
  description:
    "Write the current SharePoint Embedded provisioning details (tenant, client, container type, " +
    "container, subscription/resource group) into a project as .env, appsettings.Development.json, " +
    "and azure.yaml so a reference app can consume them. Run after provisioning.",
  inputSchema: {
    type: "object" as const,
    properties: {
      targetDir: { type: "string", description: "Project directory to write into. Default: current directory." },
      formats: {
        type: "array",
        items: { type: "string", enum: ["env", "appsettings", "azureyaml"] },
        description: "Which config files to write. Default: all three.",
      },
    },
  },
  handler: async (args) => {
    const { targetDir = process.cwd(), formats } = args as HydrateArgs;
    const state = readState();

    // Validate `formats` when provided. The declared enum is not enforced at
    // the transport boundary, so an invalid or empty value previously wrote 0
    // files yet reported success. Omitting `formats` keeps the
    // documented default (all three); a provided value must be a non-empty
    // array of known formats.
    let selectedFormats: readonly string[];
    if (formats === undefined) {
      selectedFormats = VALID_FORMATS;
    } else {
      if (!Array.isArray(formats) || formats.length === 0) {
        return {
          content: [
            {
              type: "text" as const,
              text:
                "Error: formats must be a non-empty array. " +
                `Valid values: ${VALID_FORMATS.join(", ")}. Omit "formats" to write all three.`,
            },
          ],
          isError: true,
        };
      }
      const invalid = formats.filter((f) => !(VALID_FORMATS as readonly string[]).includes(f));
      if (invalid.length > 0) {
        return {
          content: [
            {
              type: "text" as const,
              text:
                `Error: invalid format(s): ${invalid.map((f) => `'${String(f)}'`).join(", ")}. ` +
                `Valid values: ${VALID_FORMATS.join(", ")}.`,
            },
          ],
          isError: true,
        };
      }
      selectedFormats = formats;
    }

    if (!state.appId || !state.containerTypeId) {
      return {
        content: [{ type: "text" as const, text: "Error: nothing to hydrate — provision an SPE app first (project_provision)." }],
        isError: true,
      };
    }

    try {
      const dir = resolve(targetDir);
      if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

      const written: string[] = [];
      if (selectedFormats.includes("env")) {
        writeFileSync(join(dir, ".env"), envFile(state), "utf-8");
        written.push(".env");
      }
      if (selectedFormats.includes("appsettings")) {
        writeFileSync(join(dir, "appsettings.Development.json"), appSettings(state), "utf-8");
        written.push("appsettings.Development.json");
      }
      if (selectedFormats.includes("azureyaml")) {
        const azureYamlPath = join(dir, "azure.yaml");
        const generated = azureYaml(state);
        if (!existsSync(azureYamlPath)) {
          writeFileSync(azureYamlPath, generated, "utf-8");
          written.push("azure.yaml");
        } else {
          // Preserve the scaffold's (and any user-customized) azure.yaml — only
          // fill top-level keys it is MISSING; never overwrite existing content
          //. A stale host/name from the scaffold is intentionally
          // kept: the scaffold owns the architecture, hydrate must not clobber.
          const existing = readFileSync(azureYamlPath, "utf-8");
          const { content, filled } = mergeAzureYaml(existing, generated);
          if (filled.length > 0) {
            writeFileSync(azureYamlPath, content, "utf-8");
            written.push(`azure.yaml (merged; filled: ${filled.join(", ")})`);
          } else {
            written.push("azure.yaml (kept existing — scaffold config preserved)");
          }
        }
      }

      const warnings = signInConfigWarnings(state);
      const output =
        "## Config Hydrated\n\n" +
        `Wrote ${written.length} file(s) to \`${dir}\`:\n\n` +
        written.map((f) => `- \`${f}\``).join("\n") +
        "\n\n| Key | Value |\n|-----|-------|\n" +
        `| TENANT_ID | \`${state.tenantId ?? ""}\` |\n` +
        `| CLIENT_ID | \`${state.appId}\` |\n` +
        `| CONTAINER_TYPE_ID | \`${state.containerTypeId}\` |\n` +
        `| CONTAINER_ID | \`${state.containerId ?? "(pending)"}\` |\n` +
        (warnings.length
          ? "\n### ⚠️ Config warnings\n\n" + warnings.map((w) => `- ${w}`).join("\n") + "\n"
          : "") +
        // The sign-in verification advisory is about the SPA's `.env`, so only
        // append it when `.env` was actually written. Offline/non-blocking.
        (written.includes(".env") ? signInVerificationAdvisory(state) : "");

      return { content: [{ type: "text" as const, text: output }] };
    } catch (error) {
      const msg = error instanceof Error ? error.message : "Unknown error";
      return { content: [{ type: "text" as const, text: `Error hydrating config: ${msg}` }], isError: true };
    }
  },
};
